// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from "./types.ts";

//const SUPABASE_URL = "https://pnbolmtjnfdnredeoboe.supabase.co";
//const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBuYm9sbXRqbmZkbnJlZGVvYm9lIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI1MjExMDEsImV4cCI6MjA2ODA5NzEwMX0.hZZ1QoKzJ1ToS-iOcafU5Zyk_SqqDvR9_BgeaI81BWg";

// const SUPABASE_URL = "https://pnvnzjwcbnkiukumrdbj.supabase.co";
// const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBudm56andjYm5raXVrdW1yZGJqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI5MDM1NDQsImV4cCI6MjA2ODQ3OTU0NH0.2brQjJTBXEdL-SZCDVRaEsnl6BkcH8EpbzDFq7JI2YQ"

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
//   auth: {
//     storage: localStorage,
//     persistSession: true,
//     autoRefreshToken: true,
//   }
// });